# Generated by Django 4.0.4 on 2022-05-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Verse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tafseer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('verses', models.ManyToManyField(related_name='tafseer', to='Verse.verse')),
            ],
        ),
    ]
