# Generated by Django 4.0.4 on 2022-06-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafseer', '0002_alter_tafseer_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.FileField(upload_to='')),
                ('tafseers', models.ManyToManyField(related_name='intro', to='Tafseer.tafseer')),
            ],
        ),
    ]
