# Generated by Django 4.0.4 on 2022-05-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Verse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ayah', models.FileField(upload_to='')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayah', to='Verse.verse')),
            ],
        ),
    ]
