# Generated by Django 4.0.4 on 2022-05-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ayah', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ayah',
            old_name='Ayah',
            new_name='sentence',
        ),
    ]
