# Generated by Django 4.0.4 on 2022-05-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recitation',
            name='recitation',
            field=models.FileField(upload_to=''),
        ),
    ]
