# Generated by Django 4.0.4 on 2022-05-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recitation', '0002_alter_recitation_recitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recitation',
            old_name='recitation',
            new_name='audio',
        ),
    ]
