# Generated by Django 4.0.3 on 2022-04-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('verses', models.IntegerField()),
                ('revelation_place', models.CharField(max_length=16)),
                ('revelation_order', models.IntegerField()),
                ('translated_name', models.CharField(max_length=64)),
            ],
        ),
    ]
