# Generated by Django 4.0.4 on 2023-04-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('verse_count', models.IntegerField()),
                ('revelation_place', models.CharField(max_length=16)),
                ('revelation_order', models.IntegerField()),
                ('translated_name', models.CharField(max_length=64)),
                ('intro', models.CharField(blank=True, default=None, max_length=100000, null=True)),
            ],
        ),
    ]
