# Generated by Django 4.0.4 on 2022-04-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chapters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='verses',
            new_name='verse_count',
        ),
    ]
