# Generated by Django 4.0.4 on 2022-04-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hizb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hizb',
            name='verse_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
