# Generated by Django 4.0.4 on 2022-05-07 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Verse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=32)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='Verse.verse')),
            ],
        ),
    ]
