# Generated by Django 4.0.4 on 2022-05-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='translation',
            field=models.FileField(upload_to=''),
        ),
    ]
