# Generated by Django 4.0.4 on 2022-05-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Translation', '0002_alter_translation_translation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='translation',
            new_name='text',
        ),
    ]
