# Generated by Django 4.0.4 on 2022-04-30 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hizb', '0001_initial'),
        ('Rub', '0001_initial'),
        ('Juz', '0001_initial'),
        ('Chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_number', models.IntegerField()),
                ('verse_key', models.CharField(max_length=8)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='Chapters.chapter')),
                ('hizb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='Hizb.hizb')),
                ('juz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='Juz.juz')),
                ('rub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='Rub.rub')),
            ],
        ),
    ]
